### ISSUE TITLE
Vendor ID

### ISSUE THREAD

**Issue by code2prog** [rangka/quickbooks#10]
When vendor is created in return request I don'g get Vendor's ID. Is it normal? If it is, how can I get this Id number?

**Comment by basherr** [comment]
@code2prog  You would get `Id` in response. 
```
$vendor = new \Rangka\Quickbooks\Services\Vendor();
$response = $vendor->create($data);
dd($response->Id);//You should see newly created vendor id
```

**Comment by code2prog** [comment]
that works, thank you :)

**Comment by basherr** [comment]
You are welcome!
