### ISSUE TITLE
Accessing static property Rangka\Quickbooks\Services\Customer::$responseHasRoot as non static

### ISSUE THREAD

**Issue by renedekat** [rangka/quickbooks#17]
Hi,

In the Service model there is a static class variable that is access through $this-> a few time.

PHP Generates warning for this.

Shouldn't that variable declaration be:

```
protected  $responseHasRoot = true;
```

It's set to false in TaxService.php .

**Comment by renedekat** [comment]
I see you changed that, but in release 0.1.7 (which is your latest) this wasn't the case. It was calling $this->responseHasRoot which is what I spotted when using it.

**Comment by khairulashraff** [comment]
Ah darn it I must have forgotten to make a release as it was made by a contributor with some minor changes by me. My apologies on that.

v0.1.8 is now released with the fix.
