### ISSUE TITLE
Add Delete method on Service

### ISSUE THREAD

**Issue by basherr** [rangka/quickbooks#4]
First of all thanks for the great and enhanced Quickbooks package. Could you please also add delete operation on services. currently I've just modified the Service class with adding just a new method for delete operation which just works fine for Quickbooks Bill though I've not tested with other Services. Would you please add the below code to the Service or may I sent a pull request over this issue.
Thanks

```
  /**
    * Delete an entity.
    *
    * @param array $data Item information.
    * @return void
    */
    public function delete($data) {
        return parent::post($this->getResourceName() . '?operation=delete', $data)->{$this->getEntityName()};
    }
```

**Comment by khairulashraff** [comment]
Hello, I'll test it out quickly and push it sometime today.

**Comment by khairulashraff** [comment]
Added. Usage is as `load()`;

`$service->delete($id)`

Thanks.
