### ISSUE TITLE
Class resource is not working

### ISSUE THREAD

**Issue by richardhdc** [rangka/quickbooks#6]
> class QBClass extends Service {
>     /**
>      * Name of this service. Must correspond to actual objecet type in Quickbooks.
>      * @var string
>      */
>     protected static $name = 'class';
> 
>     /**
>      * Resource name of this service. Must correspond to actual objecet type in Quickbooks and in all lowercase.
>      * @var string
>      */
>     protected static $resource_name = 'Class';
> 
> }
> 

But when I changed the $name to 'Class', it works. Please verify if it should be capitalize?

**Comment by khairulashraff** [comment]
No, it should not be capitalised. That refers to the API endpoint. I don't think I ever finished using `$resource_name`.

How does it not work? Is this the same as error in #7?

**Comment by richardhdc** [comment]
Looks like everything is working now. Good job.
