### ISSUE TITLE
Service Request: can you add uploading of attachment for invoice

### ISSUE THREAD

**Issue by richardhdc** [rangka/quickbooks#8]
Service Request: can you add service for uploading of attachment for invoice

**Comment by khairulashraff** [comment]
Hello @richardhdc. I have implement it.

Usage;
```
$files = [
    [
        'path' => '/path/to/file', // Required
        'type' => 'image/png'      // Optional
        'name' => 'filename.png'   // Optional
    ]
];

$service = new \Rangka\Quickbooks\Services\Invoice;
$service->attach($id, $files);
```

You can refer to the `README.md` for some more info.

**Comment by richardhdc** [comment]
Wow! I've been trying to code it myself but you done it better. I will try it today. Good job mate!
